from pathlib import Path; import sys; sys.path.append(str(Path(__file__).resolve().parent.parent.parent / 'src'))

import QieyunEncoder as QE

assert '來' in QE.常量.所有母
assert '透' in QE.常量.所有母
assert '合' in QE.常量.所有呼
assert '開' in QE.常量.所有呼
assert '三' in QE.常量.所有等
assert '四' in QE.常量.所有等
assert 'A' in QE.常量.所有重紐
assert 'B' in QE.常量.所有重紐
assert '魚' in QE.常量.所有韻
assert '侯' in QE.常量.所有韻
assert '去' in QE.常量.所有聲
assert '入' in QE.常量.所有聲
assert '幫' in QE.常量.重紐母
assert '疑' in QE.常量.重紐母
assert '鹽' in QE.常量.重紐韻
assert '祭' in QE.常量.重紐韻
assert '麻' in QE.常量.開合兼備的韻
assert '支' in QE.常量.開合兼備的韻
assert '嚴' in QE.常量.必爲開口的韻
assert '痕' in QE.常量.必爲開口的韻
assert '文' in QE.常量.必爲合口的韻
assert '魂' in QE.常量.必爲合口的韻
assert '東' in QE.常量.開合中立的韻
assert '尤' in QE.常量.開合中立的韻
assert '灰' in QE.常量.一等韻
assert '豪' in QE.常量.一等韻
assert '咸' in QE.常量.二等韻
assert '刪' in QE.常量.二等韻
assert '清' in QE.常量.三等韻
assert '陽' in QE.常量.三等韻
assert '蕭' in QE.常量.四等韻
assert '青' in QE.常量.四等韻
assert '歌' in QE.常量.一三等韻
assert '東' in QE.常量.一三等韻
assert '麻' in QE.常量.二三等韻
assert '庚' in QE.常量.二三等韻
assert '齒' in QE.常量.所有音
assert '脣' in QE.常量.所有音
assert '知' in QE.常量.所有組
assert '端' in QE.常量.所有組
assert '去' in QE.常量.所有類
assert '古' in QE.常量.所有類
assert '山' in QE.常量.所有攝
assert '通' in QE.常量.所有攝
assert '微' in QE.常量.輕脣韻
assert '東' in QE.常量.輕脣韻
assert '夬' in QE.常量.次入韻
assert '泰' in QE.常量.次入韻
